######################################
## GLOBAL VARIABLES
######################################
WHOAMI := $(shell whoami)
PWD := $(shell pwd)
DATE := $(shell date '+%Y_%m%d_%H%M_%S')

TEST_DIR := $(shell pwd)
UVM_TRAINING := /home/ahmed/uvm_training
COMP_DIR := $(UVM_TRAINING)/verif/kernel/test/short_test

SIMULATOR := questa
ifeq ($(SIMULATOR), questa)
	BUILD_CMD := vlog 
	BUILD_CMD := $(BUILD_CMD) +incdir+/home/ahmed/Downloads/NED_IC_Design_Course/Design_Verification_UVM/uvm_1.2/uvm-1.2/src 
	OPTM_CMD := vopt 
endif

# ---> CHOOSE YOUR TARGET HERE <---
TOP_MODULE := tb_top
DATABASE := $(TOP_MODULE) glbl

#####################################
## TEST VARIABLES
#####################################
USR_OPT := $(addprefix , $(OPT))
USR_LOG := $(addprefix , $(LOG))

# ---> NEW: Default test matches the NRZ test! <---
ifeq "$(TEST_NAME)" ""
	TEST_NAME := nrz_base_test
endif

GUI  := 0
PLUSARGS ?=

ifeq ($(SIMULATOR), questa)
	SIM_CMD := vsim 
	BUILD_OPT := $(BUILD_OPT) -modelsimini /home/ahmed/modelsim_2020_libs/modelsim.ini
	BUILD_OPT := $(BUILD_OPT) -sv -mfcu 
	BUILD_OPT := $(BUILD_OPT) -work $(COMP_DIR)/work
	BUILD_OPT := $(BUILD_OPT) +define+VSIM
	BUILD_OPT := $(BUILD_OPT) -timescale=1ns/100fs
endif

# Include directories (UVM Search Paths)
BUILD_OPT := $(BUILD_OPT) +incdir+$(UVM_TRAINING)/verif/kernel/uvm_tb/sequence_item
BUILD_OPT := $(BUILD_OPT) +incdir+$(UVM_TRAINING)/verif/kernel/uvm_tb/sequence
BUILD_OPT := $(BUILD_OPT) +incdir+$(UVM_TRAINING)/verif/kernel/uvm_tb/config
BUILD_OPT := $(BUILD_OPT) +incdir+$(UVM_TRAINING)/verif/kernel/uvm_tb/interface                                
BUILD_OPT := $(BUILD_OPT) +incdir+$(UVM_TRAINING)/verif/kernel/uvm_tb/agent
BUILD_OPT := $(BUILD_OPT) +incdir+$(UVM_TRAINING)/verif/kernel/uvm_tb/scoreboard
BUILD_OPT := $(BUILD_OPT) +incdir+$(UVM_TRAINING)/verif/kernel/uvm_tb/env
BUILD_OPT := $(BUILD_OPT) +incdir+$(UVM_TRAINING)/verif/kernel/test/short_test

# =====================================================================
# ---> COMPILATION ORDER <---
# =====================================================================

# 1. Compile All Interfaces
BUILD_OPT := $(BUILD_OPT) $(UVM_TRAINING)/verif/kernel/uvm_tb/interface/bkp_intf.sv
BUILD_OPT := $(BUILD_OPT) $(UVM_TRAINING)/verif/kernel/uvm_tb/interface/out_intf.sv
BUILD_OPT := $(BUILD_OPT) $(UVM_TRAINING)/verif/kernel/uvm_tb/interface/kwr_intf.sv
BUILD_OPT := $(BUILD_OPT) $(UVM_TRAINING)/verif/kernel/uvm_tb/interface/kst_intf.sv 
BUILD_OPT := $(BUILD_OPT) $(UVM_TRAINING)/verif/kernel/uvm_tb/interface/krd_intf.sv 
BUILD_OPT := $(BUILD_OPT) $(UVM_TRAINING)/verif/kernel/uvm_tb/interface/nrz_intf.sv # <--- NEW

# 2. Compile All RTL
BUILD_OPT := $(BUILD_OPT) $(UVM_TRAINING)/design/kernel/kernel_config.sv
BUILD_OPT := $(BUILD_OPT) $(UVM_TRAINING)/design/kernel/kernel_write.sv
BUILD_OPT := $(BUILD_OPT) $(UVM_TRAINING)/design/kernel/dual_port_FIFO.sv            
BUILD_OPT := $(BUILD_OPT) $(UVM_TRAINING)/design/kernel/cdc_pulse_toggle_sync.sv  
BUILD_OPT := $(BUILD_OPT) $(UVM_TRAINING)/design/kernel/cdc_bit_sync.sv
BUILD_OPT := $(BUILD_OPT) $(UVM_TRAINING)/design/kernel/cdc_count_11bit_toggle.sv   
BUILD_OPT := $(BUILD_OPT) $(UVM_TRAINING)/design/kernel/kernel_start_tx.sv          
BUILD_OPT := $(BUILD_OPT) $(UVM_TRAINING)/design/kernel/kernel_read.sv              
BUILD_OPT := $(BUILD_OPT) $(UVM_TRAINING)/design/kernel/kernel_nrz.sv               # <--- NEW

# 3. Add Xilinx Global File (If utilizing Xilinx Primitives)
BUILD_OPT := $(BUILD_OPT) /home/ahmed/modelsim_2020_libs/glbl.v

# 4. Compile UVM Base & Project Packages
BUILD_OPT := $(BUILD_OPT) /home/ahmed/Downloads/NED_IC_Design_Course/Design_Verification_UVM/uvm_1.2/uvm-1.2/src/uvm_pkg.sv
BUILD_OPT := $(BUILD_OPT) $(UVM_TRAINING)/verif/kernel/uvm_tb/package/kernel_pkg.sv

# 5. Compile Top Module Testbenches
BUILD_OPT := $(BUILD_OPT) $(UVM_TRAINING)/verif/kernel/test/short_test/kernel_base_test.sv
BUILD_OPT := $(BUILD_OPT) $(UVM_TRAINING)/verif/kernel/test/short_test/kwr_base_test.sv
BUILD_OPT := $(BUILD_OPT) $(UVM_TRAINING)/verif/kernel/test/short_test/kst_base_test.sv 
BUILD_OPT := $(BUILD_OPT) $(UVM_TRAINING)/verif/kernel/test/short_test/krd_base_test.sv 
BUILD_OPT := $(BUILD_OPT) $(UVM_TRAINING)/verif/kernel/test/short_test/nrz_base_test.sv # <--- NEW
BUILD_OPT := $(BUILD_OPT) $(UVM_TRAINING)/verif/kernel/vlib/tb_top.sv
BUILD_OPT := $(BUILD_OPT) -l $(COMP_DIR)/compile.log

# Optimization options 
ifeq ($(SIMULATOR), questa)
	OPTM_OPT := +acc $(TOP_MODULE) glbl -o $(DATABASE) -designfile design.bin -work $(COMP_DIR)/work
	SIM_OPT := $(SIM_OPT) -modelsimini /home/ahmed/modelsim_2020_libs/modelsim.ini -L unisims_ver -L unimacro_ver -L secureip -L xpm
	SIM_OPT := $(SIM_OPT) -sv_lib /home/ahmed/Downloads/NED_IC_Design_Course/Design_Verification_UVM/uvm_1.2/uvm-1.2/lib/uvm_dpi -work $(COMP_DIR)/work
	SIM_OPT := $(SIM_OPT) $(PLUSARGS)
endif

ifeq ($(GUI), 1)
	SIM_OPT := $(DATABASE) $(SIM_OPT)
else
	SIM_OPT := -c $(DATABASE) $(SIM_OPT)
endif

SIM_OPT := $(SIM_OPT) +UVM_TESTNAME=$(TEST_NAME)
SIM_OPT := $(SIM_OPT) +UVM_CONFIG_DB_TRACE
SIM_OPT := $(SIM_OPT) -classdebug
SIM_OPT := $(SIM_OPT) -l $(TEST_NAME).log

ifeq ($(SIMULATOR), questa)
	ifeq ($(GUI), 1)
	SIM_OPT := $(SIM_OPT) -do "do wave.do; run -a; q"
	else
	SIM_OPT := $(SIM_OPT) -do "run -a; q"
	endif
endif

cov:
	dve -covdir $(COMP_DIR)/simv.vdb -full64

compile:
	$(BUILD_CMD) $(BUILD_OPT)

optimize:
	$(OPTM_CMD) $(OPTM_OPT)

run: build run_sim

run_sim: 
ifeq ($(SIMULATOR), questa) 
	$(SIM_CMD) $(SIM_OPT) $(USR_OPT)
else
	$(SIMV_CMD) $(SIM_OPT) $(USR_OPT)
endif

# Skipping optimization step because of the ModelSim Lite license limit we encountered earlier
build: compile

build_run_sim: build run_sim

clean:
	@rm -rf $(UVM_TRAINING)/verif/kernel/test/*/cm.log 
	@rm -rf $(UVM_TRAINING)/verif/kernel/test/*/DVEfiles/ 
	@rm -rf $(UVM_TRAINING)/verif/kernel/test/*/inter.vpd 
	@rm -rf $(UVM_TRAINING)/verif/kernel/test/*/*.log 
	@rm -rf $(UVM_TRAINING)/verif/kernel/test/*/ucli.key
	@rm -rf $(UVM_TRAINING)/verif/kernel/test/*/wlft*
	@rm -rf $(UVM_TRAINING)/verif/kernel/test/*/vsim.wlf
	@rm -rf $(UVM_TRAINING)/verif/kernel/test/*/*.bin
	@rm -rf $(UVM_TRAINING)/verif/kernel/test/*/tr_db.log
	@rm -rf $(COMP_DIR)/compile.log
	@rm -rf $(COMP_DIR)/work
	@rm -rf $(COMP_DIR)/design.bin
	@rm -rf $(COMP_DIR)/csrc  
	@rm -rf $(COMP_DIR)/simv  
	@rm -rf $(COMP_DIR)/simv.cst  
	@rm -rf $(COMP_DIR)/simv.daidir  
	@rm -rf $(COMP_DIR)/simv.vdb  
	@rm -rf $(COMP_DIR)/vc_hdrs.h