////////////////////////////////////////////////////////////////////////////////
//
//  Filename      : mac_rx_env.sv
//  Author        : Ahmed Ali
//  Creation Date : 16/04/2026
//
//  Copyright 2026 Avant Labs PVT LTD. All Rights Reserved.
//
//  No portions of this material may be reproduced in any form without
//  the written permission of:
//
//    First Floor, Jumaira Arcade,
//    Fateh Jang Road,
//    Sector F-17, Islamabad, 45230
//
//  All information contained in this document is Avant Labs PVT LTD
//  company private, proprietary and trade secret.
//
//  Description
//  ===========
//  UVM environment for Ethernet MAC RX verification
////////////////////////////////////////////////////////////////////////////////

`ifndef MAC_RX_ENV_SV
`define MAC_RX_ENV_SV

class mac_rx_env extends uvm_env;
  `uvm_component_utils(mac_rx_env)

  mac_rx_env_cfg         cfg;
  
  // ---> 1. ADD THE VIRTUAL INTERFACE PROPERTY <---
  virtual mac_rx_if      vif; 

  phy_mac_agent          phy_agnt;
  cpu_mac_agent          cpu_agnt;
  whitebox_mac_agent     wb_agnt;
  mac_rx_scoreboard      scb;

  function new(string name="mac_rx_env", uvm_component parent=null);
    super.new(name, parent);
  endfunction

  virtual function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    
    // Grab the config object generated by the Base Test
    if(!uvm_config_db#(mac_rx_env_cfg)::get(this, "", "cfg", cfg))
      `uvm_fatal("NO_CFG", "Environment could not find mac_rx_env_cfg!")

    // ---> 2. GRAB THE INTERFACE FROM THE CONFIG DB <---
    // This allows the test (which sits above the env) to access env.vif.rx_ctl
    if(!uvm_config_db#(virtual mac_rx_if)::get(this, "", "vif", vif))
      `uvm_fatal("NO_VIF", "Environment could not find mac_rx_if!")

    // Build Agents
    phy_agnt = phy_mac_agent::type_id::create("phy_agnt", this);
    cpu_agnt = cpu_mac_agent::type_id::create("cpu_agnt", this);
    wb_agnt  = whitebox_mac_agent::type_id::create("wb_agnt", this);
    
    // Build Scoreboard
    scb = mac_rx_scoreboard::type_id::create("scb", this);
  endfunction

  virtual function void connect_phase(uvm_phase phase);
    super.connect_phase(phase);
    
    // Connect Agent Monitors to Scoreboard
    phy_agnt.mon.mon_ap.connect(scb.phy_export);
    cpu_agnt.mon.mon_ap.connect(scb.cpu_export);
  endfunction

endclass

`endif