`ifndef LINE_RX_MONITOR_SV
`define LINE_RX_MONITOR_SV

class line_rx_monitor extends uvm_monitor;
  `uvm_component_utils(line_rx_monitor)

  uvm_analysis_port#(tx_uart) mon_analysis_port;
  virtual uart_unified_intf   vif;
  
  // ADDED: Handle for dynamic configuration
  uart_config cfg;
  
  parameter clock_frequency = 32'd55_296_000;

  function new(string name="line_rx_monitor", uvm_component parent=null);
    super.new(name, parent);
  endfunction 

  virtual function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    if (!uvm_config_db#(virtual uart_unified_intf)::get(this, "", "uart_unified_intf", vif))
      `uvm_fatal("LINE_RX_MONITOR", "Could not get unified vif")
      
    // ADDED: Fetch the configuration object generated by eiu_env
    if (!uvm_config_db#(uart_config)::get(this, "", "uart_cfg", cfg))
      `uvm_fatal("LINE_RX_MONITOR", "Could not get uart_cfg from DB!")
      
    mon_analysis_port = new ("mon_analysis_port", this);
  endfunction 

  // Ensure this uses run_phase!
  virtual task run_phase(uvm_phase phase);
    super.run_phase(phase);
    collect_data();
  endtask 

  task collect_data();
    tx_uart pkt;
    int clock_delay;
    logic [31:0] shift_reg; 

    // ADDED: Use the dynamic config
    int local_baudrate   = cfg.baudrate;
    int local_data_width = cfg.data_width;
    bit local_parity_en  = cfg.parity_en;

    forever begin
      @(negedge vif.rx); // Wait for physical start bit

      pkt = tx_uart::type_id::create("pkt");

      pkt.baudrate        = local_baudrate;
      pkt.data_width      = local_data_width;
      pkt.parity_en       = local_parity_en;
      pkt.parity_odd_even = cfg.parity_odd_even;

      if (local_baudrate != 0) clock_delay = clock_frequency / local_baudrate;
      else                     clock_delay = clock_frequency / 115200; 

      repeat(clock_delay / 2) @(posedge vif.clk); // Center sample
      shift_reg = 0;

      for (int i = 0; i < local_data_width; i++) begin
        repeat(clock_delay) @(posedge vif.clk);
        shift_reg[i] = vif.rx; 
      end
      pkt.data_in = shift_reg; 
      
      if (local_parity_en) begin
        repeat(clock_delay) @(posedge vif.clk);
        pkt.sampled_parity = vif.rx;
      end

      // Wait for stop bit
      repeat(clock_delay) @(posedge vif.clk);

      mon_analysis_port.write(pkt);

      begin
        string frame_str = "[0]_"; 
        frame_str = {frame_str, "["};
        for (int i = 0; i < local_data_width; i++) begin
          frame_str = {frame_str, $sformatf("%b", pkt.data_in[i])}; 
        end
        frame_str = {frame_str, "]"};

        if (local_parity_en == 1'b1) begin
          frame_str = {frame_str, "_[", $sformatf("%b", pkt.sampled_parity), "]"}; 
        end
        frame_str = {frame_str, "_[1]"}; 

        `uvm_info("LINE_RX_MONITOR", $sformatf("Sampled Wire Frame:   %s (Width: %0d, Baud: %0d)", 
                  frame_str, pkt.data_width, pkt.baudrate), UVM_LOW)
      end
    end
  endtask 

endclass

`endif