/*`ifndef LINE_RX_DRIVER_SV
`define LINE_RX_DRIVER_SV

class line_rx_driver extends uvm_driver #(tx_uart);
  `uvm_component_utils(line_rx_driver)

  virtual uart_unified_intf vif;
  parameter clock_frequency = 32'd44_236_800;

  function new(string name = "line_rx_driver", uvm_component parent=null);
    super.new(name, parent);
  endfunction

  virtual function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    if (!uvm_config_db#(virtual uart_unified_intf)::get(this, "", "uart_unified_intf", vif))
      `uvm_fatal("LINE_RX_DRIVER", "Could not get unified vif")
  endfunction 

  virtual task run_phase(uvm_phase phase);
    super.run_phase(phase);
    
    vif.rx <= 1'b1; // Idle state for UART is HIGH

    `uvm_info("DRV_PROBE", "Driver started. Waiting 2us for system settle...", UVM_NONE)
    
    // Wait 2us (Matches ETH drivers exactly)
    #2000ns; 

    `uvm_info("DRV_PROBE", "Driver awake! Entering main loop.", UVM_NONE)

    forever begin
      seq_item_port.get_next_item(req); 
      
      `uvm_info("DRV_PROBE", $sformatf("Got Packet! Data: 'h%0h | Baud: %0d", req.data_in, req.baudrate), UVM_NONE)
      drive_item(req);
      
      seq_item_port.item_done();
    end
  endtask 

  virtual task drive_item(tx_uart drv_pkt); 
    int safe_data_width;
    bit [8:0] masked_data; 
    real bit_period_ns;
    
    // 1. Safety Checks
    if (drv_pkt.baudrate == 0) drv_pkt.baudrate = 115200;
    
    if (drv_pkt.data_width > 9 || drv_pkt.data_width == 0) begin
        safe_data_width = 8;
    end else begin
        safe_data_width = drv_pkt.data_width;
    end

    masked_data = drv_pkt.data_in & ((1 << safe_data_width) - 1);
    
    // Calculate exact duration of 1 bit in nanoseconds (e.g. 1000000000 / 115200 = 8680 ns)
    bit_period_ns = 1000000000.0 / drv_pkt.baudrate;
    
    // 2. Start Bit (Drive Low)
    vif.rx <= 1'b0;
    #(bit_period_ns * 1ns);

    // 3. Data Bits (LSB First)
    for (int i = 0; i < safe_data_width; i++) begin
      vif.rx <= masked_data[i];
      #(bit_period_ns * 1ns);
    end

    // 4. Parity Bit
    if (drv_pkt.parity_en) begin
        vif.rx <= drv_pkt.expected_parity; 
        #(bit_period_ns * 1ns);
    end

    // 5. Stop Bit (Drive High)
    vif.rx <= 1'b1;
    #(bit_period_ns * 1ns);
    
    // Gap: Wait 2 full bit periods to ensure the RTL state machine completely resets
    #(bit_period_ns * 2 * 1ns);

    `uvm_info("DRV_PROBE", "=== Packet Successfully Transmitted ===", UVM_NONE)
  endtask
endclass

`endif*/

`ifndef LINE_RX_DRIVER_SV
`define LINE_RX_DRIVER_SV

class line_rx_driver extends uvm_driver #(tx_uart);
  `uvm_component_utils(line_rx_driver)

  virtual uart_unified_intf vif;
  uart_config cfg;
  
  parameter clock_frequency = 32'd44_236_800;

  function new(string name = "line_rx_driver", uvm_component parent=null);
    super.new(name, parent);
  endfunction

  virtual function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    
    if (!uvm_config_db#(virtual uart_unified_intf)::get(this, "", "uart_unified_intf", vif))
      `uvm_fatal("LINE_RX_DRIVER", "Could not get unified vif")
      
    // Fetch the dynamic configuration object generated by eiu_env
    if(!uvm_config_db#(uart_config)::get(this, "", "uart_cfg", cfg))
      `uvm_fatal("LINE_RX_DRIVER", "Could not get uart_cfg")
  endfunction 

  virtual task run_phase(uvm_phase phase);
    super.run_phase(phase);
    
    vif.rx <= 1'b1; // Idle state for UART is HIGH

    `uvm_info("DRV_PROBE", "Driver started. Waiting 2us for system settle...", UVM_NONE)
    #2us; 

    `uvm_info("DRV_PROBE", "Waiting 150us for EIU Hardware to acquire Baudrate lock from Backplane...", UVM_NONE)
    #150us;

    `uvm_info("DRV_PROBE", "Driver awake! Entering main loop.", UVM_NONE)

    forever begin
      seq_item_port.get_next_item(req); 
      
      // Drive the packet cycle-accurately
      drive_item(req);
      
      seq_item_port.item_done();
    end
  endtask 

  virtual task drive_item(tx_uart drv_pkt); 
    int safe_data_width;
    int clock_delay; // Use integers for exact cycle counting

    // 1. Safety Checks
    if (drv_pkt.data_width > 9 || drv_pkt.data_width == 0) begin
        safe_data_width = 8;
    end else begin
        safe_data_width = drv_pkt.data_width;
    end

    // Calculate exact number of 44.2368MHz clock cycles per UART bit
    if (cfg.baudrate != 0) 
        clock_delay = clock_frequency / cfg.baudrate;
    else
        clock_delay = clock_frequency / 115200; 

    // Align to the next clock edge
    @(posedge vif.clk);

    // 2. Start Bit (Drive Low)
    vif.rx <= 1'b0;
    repeat(clock_delay) @(posedge vif.clk);

    // 3. Data Bits (LSB First)
    for (int i = 0; i < safe_data_width; i++) begin
        vif.rx <= drv_pkt.data_in[i];
        repeat(clock_delay) @(posedge vif.clk);
    end

    // 4. Parity Bit (Optional)
    if (cfg.parity_en) begin
        vif.rx <= drv_pkt.sampled_parity;
        repeat(clock_delay) @(posedge vif.clk);
    end

    // 5. Stop Bit (Drive High)
    vif.rx <= 1'b1;
    repeat(clock_delay) @(posedge vif.clk);
    
    // Extra Idle Time between packets (Safety padding to avoid trampling the stop bit)
    repeat(clock_delay) @(posedge vif.clk);

    // Printed at UVM_LOW so you can see it in the terminal!
    `uvm_info("LINE_RX_DRIVER", $sformatf("Injected byte into physical RX pin: %0h", drv_pkt.data_in[7:0]), UVM_LOW)
  endtask

endclass

`endif